# This is a basic workflow to help you get started with Actions

name: Data Provider

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '5 12 * * *'
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
     
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: the shell script
      run: ./dresden-json2csv.sh data.config

    # Stores a resulting file for e.g. later download
    - name: archive resulting csv file
      uses: actions/upload-artifact@v1
      with:
          name: resulting csv file
          path: data/de_dresden_www.csv
    # Runs a set of commands using the runners shell
    - name: show file content 
      shell: sh
      run: |
        fn="data/de_dresden_www.csv"
        echo "contents of $fn"
        echo "----8X----"
        cat "$fn"
        echo "----X8----"
        printf "done.\n" 

    - name: commit resulting file to repository 
      shell: sh
      run: |
        fn="data/de_dresden_www.csv"
        git config user.name ci-script
        git config user.email ci-script@users.noreply.github.com
        git add "$fn"
        git commit "$fn" -m "add o-file"
        git push origin master
